export const STATUS_CODES = {
  OK: 200,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

export const SHOULD_RETRY = [
  STATUS_CODES.INTERNAL_SERVER_ERROR,
  STATUS_CODES.BAD_GATEWAY,
  STATUS_CODES.SERVICE_UNAVAILABLE,
  STATUS_CODES.GATEWAY_TIMEOUT,
  STATUS_CODES.TOO_MANY_REQUESTS,
];

export const RETRY_AFTER_HEADER = 'Retry-After';